### ISSUE TITLE
Docker entrypoint cannot be found

### ISSUE THREAD

**Issue by juliangehring** [tanmaykm/JuliaDockerImages#1]
Starting the julia docker with a defined entrypoint

``` julia
sudo docker run -it --entrypoint="/usr/bin/julia" julialang/julia:v0.3.8 ## 1
sudo docker run -it --entrypoint="/usr/bin/julia" julialang/julia:v0.4.0 ## 2
```

fails for 0.3.8 with

```
exec: "/usr/bin/julia": stat /usr/bin/julia: no such file or directory
FATA[0000] Error response from daemon: Cannot start container ecf8709b4daaf4c07f68a2087fff3900b049cb1d02db1ae7e2badda89de3a158: [8] System error: exec: "/usr/bin/julia": stat /usr/bin/julia: no such file or directory
```

and for 0.4.0

```
exec: "/usr/bin/julia": stat /usr/bin/julia: no such file or directory
FATA[0000] Error response from daemon: Cannot start container fb2f32d69e1ec00464fbee07c320d19ba8690a0b6643f9c140c8a5654059fc41: [8] System error: exec: "/usr/bin/julia": stat /usr/bin/julia: no such file or directory
```

In contrast, starting the image w/o entrypoint and calling julia from the root shell works:

```
sudo docker run -it julialang/julia:v0.3.8

julia
```

Docker version: `1.6.2, build 7c8fca2`
Docker image: `julialang/julia,, v0.3.8, 7906420eb20c`
System info: `Linux crick 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by tanmaykm** [comment]
Julia is at `/opt/julia` instead in the latest image.
So `sudo docker run -it --entrypoint="/opt/julia/bin/julia" julialang/julia:v0.3.8` should work.

The doc needs to be updated.
Thanks for pointing it out!

**Comment by juliangehring** [comment]
Nice, using `/opt/julia/bin/julia` as new entry point works.

`docker run -it --net="host" --entrypoint="/usr/local/bin/ipython" julialang/julia:v0.3.8 notebook --profile julia` seems to fail due to the same reason. What would the correct path be here?  I couldn't find an `ipython` binary inside the image.

**Comment by tanmaykm** [comment]
Hmm... Seems to run fine with a locally built image, but the image downloaded from dockerhub does have this problem. That needs some investigation.

Can you try building locally in the meantime?

`git clone https://github.com/tanmaykm/JuliaDockerImages.git && docker build -t julialang/julia:v0.3.x JuliaDockerImages/base/v0.3` should do that.

**Comment by juliangehring** [comment]
With the locally built image, iJulia works fine.

**Comment by tanmaykm** [comment]
Ok... the dockerhub image is probably corrupted. I have initiated a new build.
If the problem persists, will push a locally built image instead.

**Comment by juliangehring** [comment]
IJulia nows works fine with the new images for v0.3.9 and v0.4.0. Thanks for the quick fix.

**Comment by juliangehring** [comment]
All fine now: e3dae5cf8d3fca106efcae1087d1b529611669d8

Works like a charm.

**Comment by tanmaykm** [comment]
Glad that it worked.
