### ISSUE TITLE
v0.5.0 tagged image

### ISSUE THREAD

**Issue by dreammaker** [tanmaykm/JuliaDockerImages#12]
I noticed that there isn't a v0.5.0 tagged image [here](https://hub.docker.com/r/julialang/julia/tags/), only v0.5.0-dev.  Now that julia v0.5.0 has been released, could you add a tagged image so that we can reference it in a Dockerfile?  Thanks.

**Comment by tanmaykm** [comment]
Sure. Will do that after https://github.com/tanmaykm/JuliaDockerImages/pull/13 and incorporate the new Jupyter version for Julia v0.5 as well.

**Comment by tanmaykm** [comment]
Julia v0.5 docker image is now tagged.

**Comment by dreammaker** [comment]
Thank you!
