### ISSUE TITLE
juliaboxpkgdist:v0.3.12 to match current juliabox.com

### ISSUE THREAD

**Issue by IanButterworth** [tanmaykm/JuliaDockerImages#18]
Could juliaboxpkgdist:v0.3.12 be updated to match what's currently available on juliabox.com?

Probably irrelevant info, but it's currently
0.3.12
0.4.6
0.5.0-dev

on juliabox.com its
0.3.12
0.4.7
0.5.0
0.6.0-dev

**Comment by tanmaykm** [comment]
The `Dockerfile` is already same as what is live on JuliaBox. It is tagged `latest` now (will likely move to a date based tag next) to indicate that it has the latest patch versions.

A ready image with this tag is not available on dockerhub though and you may have to build it locally, see https://groups.google.com/d/msg/julia-box/a7vmohiSdX4/0AxJoMpDAwAJ

**Comment by IanButterworth** [comment]
Done and tagged 
https://hub.docker.com/r/ianshmean/juliaboxpkgdist/
