### ISSUE TITLE
Serving through tmpnb fails with 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by tgenewein** [tanmaykm/JuliaDockerImages#5]
I am trying to run IJulia notebooks through tmpnb with the juliaboxminpkgdist:v0.3.11 image. The image itself runs fine but when I try to serve it through tmpnb, the tmpnb container crashes and the logs (for the tmpnb) yield the following:

```
Traceback (most recent call last):
  File "orchestrate.py", line 340, in <module>
    main()
  File "orchestrate.py", line 320, in main
    ioloop.run_sync(pool.heartbeat)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 418, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 189, in heartbeat
    yield tasks
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 464, in callback
    result_list = [i.result() for i in children]
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/srv/tmpnb/spawnpool.py", line 227, in _launch_container
    container_config=self.container_config)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 633, in run
    yielded = self.gen.send(value)
  File "/srv/tmpnb/dockworker.py", line 139, in create_notebook_server
    host_port = container_network[0]['HostPort']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Here's the command I used to start the tmpnb image

```
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image="julialang/juliaboxminpkgdist:v0.3.11" --allow_origin="*" --command="/usr/local/bin/ipython notebook --profile julia --no-browser --port {port} --ip=* --NotebookApp.allow_origin=* --NotebookApp.base_url={base_path}" --cull-timeout=300 --cull_period=60
```

I found somebody (@gpillemer) with the same problem but using a different image in https://github.com/jupyter/tmpnb/issues/125 but I could not get it to work.

Anyway, it might be good to extend the README once this is solved to explain how to server through tmpnb.

Any help is highly appreciated

**Comment by tgenewein** [comment]
Same error also mentioned here: https://github.com/jupyter/tmpnb/issues/175
@parente perhaps you could shed some light into this and the corresponding solution? (sorry to bother you, but I still haven't figured it out)

**Comment by parente** [comment]
The exception you posted seems to come up whenever the container fails to launch and bind to a port, regardless of the problem. Try launching your container using the same command you give tmpnb to make sure there's nothing amiss. Are you exposing a port in the Dockerfile for your image?

**Comment by tgenewein** [comment]
Thanks a lot @parente - I thought there was something wrong with the image but (of course) that was not the case. Actually, the container simply exits instantly if it is not run with docker's `-it` flag. Since I don't know how to run an image through tmpnb with `-it` (but I'd be curious to know if there's a way to do it), I used [tini](https://github.com/krallin/tini) in a custom image that builds upon the original image and set the entrypoint to tini.

Just for future reference here's a complete description: I created my own `dockerfile` with the following contents (to be sure port 8888 is also exposed):

```
# Docker file for JuliaBox Minimal
# Tag: tgenewein/jupyternotebook
# Version:v0.3.11

FROM julialang/juliaboxminpkgdist:v0.3.11

MAINTAINER Tim Genewein

# Add Tini
ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

EXPOSE 8888
```

Then, the dockerfile is built with `docker build -t tgenewein/jupyternotebook .`

Finally, to serve the image through tmpnb:

```
export TOKEN=$( head -c 30 /dev/urandom | xxd -p )
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image="tgenewein/jupyternotebook" --allow_origin="*" --command="ipython notebook --profile julia --no-browser --port {port} --ip=* --NotebookApp.allow_origin=* --NotebookApp.base_url={base_path}" --cull-timeout=300 --cull_period=60
```

This works fine for me on a AWS t2.micro instance, even though simultaneously opening more than one notebook server seems to push the system way beyond its limits (which is a bit strange...)

Anyway, thanks for the help!
