### ISSUE TITLE
v0.3.12 tagged images missing

### ISSUE THREAD

**Issue by IanButterworth** [tanmaykm/JuliaDockerImages#6]
It appears that there aren't any v0.3.12 tagged images available for base julia or the juliabox images even though it's highlighted as available.

**Comment by tanmaykm** [comment]
Yes, I see that. Strangely, the build details show the build to have gone through successfully for the last two times.

I'm triggering a fresh build now.

**Comment by tanmaykm** [comment]
I'm able to see v0.3.12 in the tags now (https://hub.docker.com/r/julialang/julia/tags/).
@ianshmean can you try?

**Comment by IanButterworth** [comment]
Indeed, I can. Not in the juliabox dists but I assume julia was first to build..

**Comment by tanmaykm** [comment]
Yes. Dockerhub builds do take quite a while. Building locally can be faster.

**Comment by IanButterworth** [comment]
Ok. Thanks!
